name: Build iOS app and create .ipa

on:
  push


jobs:
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
#    - name: Cache Maven dependencies
#      uses: actions/cache@v2
#      with:
#        path: ~/.m2/repository
#        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#        restore-keys: ${{ runner.os }}-maven-
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 17
        cache: 'maven'
    - name: Cache GraalVM installation
      uses: actions/cache@v2
      with:
        path: ~/.sdkman/candidates/graalvm/current
        key: ${{ runner.os }}-graalvm-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-graalvm-
    - name: Setup GraalVM built by Gluon
      uses: gluonhq/setup-graalvm@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.GLUON_IOS_BASE64 }}
        p12-password: ${{ secrets.GLUON_IOS_CERTIFICATES_PASSWORD }}
    - name: Fix file permissions
      run: chmod +x mvnw
    - name: Build iOS app and create .ipa
      run: |
        ./mvnw -Pios gluonfx:build gluonfx:package
        mkdir -p $HOME/artifacts
        mv target/client/*.ipa $HOME/artifacts/app.ipa
    - name: Upload .ipa as artifact
      uses: actions/upload-artifact@v2
      with:
        name: app
        path: $HOME/artifacts/app.ipa
