name: Build iOS app

on:
  push

jobs:
  build-ios:
    if: "contains(github.event.head_commit.message, '[CI iOS]')"
    runs-on: macos-latest
    steps:
#      - name: Wait for linting to finish
#        uses: lewagon/wait-on-check-action@v1.3.1
#        with:
#          ref: ${{ github.ref }}
#          repo-token: ${{ secrets.GITHUB_TOKEN }}
#          check-name: 'Format'
#          wait-interval: 10
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 20
          cache: 'maven'
      - name: Cache GraalVM installation
        uses: actions/cache@v2.1.4
        with:
          path: ~/.sdkman/candidates/graalvm/current
          key: ${{ runner.os }}-graalvm-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-graalvm-
      - name: Setup GraalVM built by Gluon
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install HomeBrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - name: Extra stuff
        run: |
          brew install libusbmuxd
          brew install libimobiledevice

      - uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.GLUON_IOS_BASE64 }}
          p12-password: ${{ secrets.GLUON_IOS_CERTIFICATES_PASSWORD }}
      - name: Fix file permissions
        run: chmod +x mvnw
      - name: Create file
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          touch ~/Library/MobileDevice/Provisioning\ Profiles/4d9ad007-c0c7-481f-b36b-aa21730c7d79.mobileprovision
      - name: Write secret to file
        run: |
          echo "${{ secrets.PROVISION_PROFILE }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/4d9ad007-c0c7-481f-b36b-aa21730c7d79.mobileprovision
      - name: Build iOS app and create .ipa
        run: |
          ./mvnw -Pios gluonfx:build gluonfx:package
      - name: Upload .ipa as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: target/gluonfx/arm64-ios/ProductivityApp.ipa
